name: 🐛 Bug Report
description: File a bug report for docker-gunbot
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out all fields. Issues without details may be closed.
        Before submitting, check the most common issues below 👇

  - type: markdown
    attributes:
      value: |
        ### ⚠️ Common Issues (check before posting)
        - **Port already in use** → Make sure port `5555` or `5000` isn't taken by another container.
        - **Permissions or empty data folder** → Verify your `PUID` and `PGID` (e.g. run `id docker` on Synology and adjust docker-compose.yml).
        - **Container fails to start** → Check the logs with `docker logs gunbot` for missing `/data` mount or wrong volume mapping.
        - **Update issues** → Remove the old container and recreate with `docker pull magicdude4eva/gunbot:latest`.
        - **Licensing errors** → Ensure your Gunbot key matches the configured exchange and wallet.

  - type: checkboxes
    id: common_issues_checked
    attributes:
      label: Have you checked the common issues above?
      description: Please confirm that none of these solve your problem.
      options:
        - label: Yes, none of the above apply
          required: true

  - type: input
    id: gunbot_version
    attributes:
      label: Gunbot version
      description: The version you're running (from container logs or Gunbot UI)
      placeholder: e.g. v30.6.7
    validations:
      required: true

  - type: input
    id: operating_system
    attributes:
      label: Operating system
      description: Your host OS or NAS model
      placeholder: e.g. Synology DSM 7.2, Ubuntu 22.04, macOS
    validations:
      required: true

  - type: textarea
    id: data_directory
    attributes:
      label: Output of "ls -ltra /data"
      description: Run this inside the container or mapped volume.
      placeholder: |
        Paste the output here, e.g.
        drwxr-xr-x  1 docker docker  4096 Oct 22 20:05 .
        drwxr-xr-x  1 root   root    4096 Oct 22 19:55 ..
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: Include logs or steps to reproduce.
      placeholder: |
        Steps:
        1. Start container
        2. Observe error XYZ in logs
        3. Expected vs actual result
    validations:
      required: true
