name: Sync Docker Hub README
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/sync-dockerhub-readme.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: magicdude4eva/gunbot-colorised
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
